name: Push openml-java packages to maven central repository

on:
  push:
    tags:
      - '*.*.*'   # release tags
    branches:
      - 'master'
      - 'hf-*'    # hotfix branches
jobs:

  publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          git fetch -f --tags
          echo exit code $?
          git tag --list

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Publish maven package
        run: mvn deploy -B -Prelease --batch-mode -DskipTests=true
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USER }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASS }}
          PGP_KEY_ID: ${{ secrets.PGP_KEY_ID }}
          PGP_PASS: ${{ secrets.PGP_PASS }}
